import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react"; 

export default function Home() {

  const [novaCor, setNovaCor] = useState("bg-vermelho");

  const mudarCor = () => {
    if (novaCor === "bg-vermelho") {  
      setNovaCor("bg-azul");
    } else if (novaCor === "bg-azul") {
      setNovaCor("bg-roxo");
    } else {
      setNovaCor("bg-vermelho");
    }
  }
  return (

    <>
      <Head>
        <title>useState</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>

       <h1>useState</h1>

       <div className={styles.display}>
        <div className={styles[novaCor]}>
          <p>Clique no botão para mudar a cor</p>
        </div>
        <button onClick={mudarCor}>Mudar Cor</button>
       </div>
      </main>
    </>
  );
}
